### ISSUE TITLE
when i use distribution training, i met an error which i use what i can try, but i still can't finish. would mind help me  

### ISSUE THREAD

**Issue by xiaohutongxue-sunny** [guoqincode/Open-AnimateAnyone#108]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 44522) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_hack.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-01-24_20:20:12
  host      : 5038d4aa163f
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 44523)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-24_20:20:12
  host      : 5038d4aa163f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 44522)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by guoqincode** [comment]
Hello, it looks like your server has a bug with distributed training... Sorry, I don't really understand how distributed training works, so I may not be able to help you.

**Comment by fenghan0430** [comment]
hello. Can you provide a complete error report? A configuration file error can also prevent distributed training from running.

**Comment by xiaohutongxue-sunny** [comment]
> hello. Can you provide a complete error report? A configuration file error can also prevent distributed training from running.

![2024-01-30 14-55-51 的屏幕截图](https://github.com/guoqincode/Open-AnimateAnyone/assets/73432611/13da1b2e-1b00-4d24-b8c5-232a9845296c)
![2024-01-30 14-56-12 的屏幕截图](https://github.com/guoqincode/Open-AnimateAnyone/assets/73432611/dcea4333-4c0e-4975-a51d-bc7fc3496f6f)
the other one is load issue, i cant load stable diffusion. all errors are here. i changed code not using from_pretrained instead of make a object (ReferenceNet() replace ReferenceNet.from_pretrained(pretrained_model_path, subfolder="unet"))

**Comment by xiaohutongxue-sunny** [comment]
> Hello, it looks like your server has a bug with distributed training... Sorry, I don't really understand how distributed training works, so I may not be able to help you.

i finish the bug which caused by stable-diffusion, my stable-diffusion checkpoint includes some error that leads to model can't load successfully.  it's amazing

**Comment by Valentino-L** [comment]
Hello! I am having the same error as you did. I'm only running on a single GPU. Could you show me exactly how you solved this problem?

Thanks a lot!

**Comment by fenghan0430** [comment]
Have you set all the training parameters correctly?I wrote an instruction to start the first stage of training.In my git warehouse.

**Comment by fenghan0430** [comment]
> Hello! I am having the same error as you did. I'm only running on a single GPU. Could you show me exactly how you solved this problem?
> 
> Thanks a lot!

Have you set all the training parameters correctly?I wrote an instruction to start the first stage of training.In my git.

**Comment by xiaohutongxue-sunny** [comment]
> Hello! I am having the same error as you did. I'm only running on a single GPU. Could you show me exactly how you solved this problem?
> 
> Thanks a lot!

You can solve in two ways:1) change the distribution training instead of normal training.2) give me more details. same problems but different solutions.

**Comment by Valentino-L** [comment]
I found out that it was actually an OOM error. I solved it by adjusting the config file. Thanks a lot!
