### ISSUE TITLE
how to fix triton for windows

### ISSUE THREAD

**Issue by EKI-INDRADI** [guoqincode/Open-AnimateAnyone#123]
```sh

python -m demo.gradio_animate
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
V:\_ANIMATION\ANIMATE_ANYONE_WINDOWS\Open-AnimateAnyone\demo\gradio_pipeline.py:15: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Initializing AnimateAnyone Pipeline...
Traceback (most recent call last):
  File "D:\__________________INSTALL\ANACONDA\envs\animate_anyone\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\__________________INSTALL\ANACONDA\envs\animate_anyone\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "V:\_ANIMATION\ANIMATE_ANYONE_WINDOWS\Open-AnimateAnyone\demo\gradio_animate.py", line 10, in <module>
    animator = AnimateAnyone()
  File "V:\_ANIMATION\ANIMATE_ANYONE_WINDOWS\Open-AnimateAnyone\demo\animate.py", line 41, in __init__
    config  = OmegaConf.load(config)
  File "D:\__________________INSTALL\ANACONDA\envs\animate_anyone\lib\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'V:\\_ANIMATION\\ANIMATE_ANYONE_WINDOWS\\Open-AnimateAnyone\\configs\\prompts\\animation_stage_2_hack.yaml'


```

please fix like this 

https://github.com/magic-research/magic-animate (linux base)

https://github.com/sdbds/magic-animate-for-windows (windows fix without triton)

**Comment by EKI-INDRADI** [comment]
fix triton & animation_stage_2_hack.yaml & sd15_mmv1.ckpt

create file  Open-AnimateAnyone/configs/prompts/animation_stage_2_hack.yaml & copy from animation_stage_2.yaml

buka : https://huggingface.co/guoyww/animatediff/tree/main 
download : mm_sd_v15.ckpt
taro di folder & rename : /Open-AnimateAnyone/pretrained_models/motion_unet/sd15_mmv1.ckpt
