### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by JS-an** [guoqincode/Open-AnimateAnyone#71]
Traceback (most recent call last):
  File "/home/allen/yes/envs/animate/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/allen/yes/envs/animate/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/allen/item/Open-AnimateAnyone/demo/gradio_animate.py", line 8, in <module>
    from demo.animate import AnimateAnyone
  File "/home/allen/item/Open-AnimateAnyone/demo/animate.py", line 20, in <module>
    from models.hack_poseguider_v2 import Hack_PoseGuider as PoseGuider
ModuleNotFoundError: No module named 'models.hack_poseguider_v2'

**Comment by guoqincode** [comment]
I fixed the bug.
