### ISSUE TITLE
No module named 'models.hack_poseguider_v2'

### ISSUE THREAD

**Issue by wangxr1999** [guoqincode/Open-AnimateAnyone#74]
Traceback (most recent call last):
  File "/opt/conda/envs/animate/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/animate/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/home/code/workspace/AnimateAnyone-unofficial/demo/gradio_animate.py", line 8, in <module>
    from demo.animate import AnimateAnyone
  File "/mnt/home/code/workspace/AnimateAnyone-unofficial/demo/animate.py", line 20, in <module>
    from models.hack_poseguider_v2 import Hack_PoseGuider as PoseGuider
ModuleNotFoundError: No module named 'models.hack_poseguider_v2'

**Comment by saidkaban** [comment]
Had a similar issue, might be related to this: https://github.com/guoqincode/Open-AnimateAnyone/issues/48
