### ISSUE TITLE
sample = sample + latent_pose

### ISSUE THREAD

**Issue by WenB777** [guoqincode/Open-AnimateAnyone#80]
感谢release，请问这里hack_unet2d.py和hack_unet3d.py对pose的操作是合理的吗？与animateanyone论文中的描述是一致的吗？

**Comment by guoqincode** [comment]
hack是我自己实现的，非hack的是原文的（非常难控制pose，需要大规模数据+overfit）

**Comment by WenB777** [comment]
原来如此，感谢大佬！

**Comment by WenB777** [comment]
> hack是我自己实现的，非hack的是原文的（非常难控制pose，需要大规模数据+overfit）

原来如此，感谢大佬，数据量小的话hack的效果更好些是吗？

**Comment by guoqincode** [comment]
> > hack是我自己实现的，非hack的是原文的（非常难控制pose，需要大规模数据+overfit）
> 
> 原来如此，感谢大佬，数据量小的话hack的效果更好些是吗？

对，即使数据量大，我也建议使用hack

**Comment by MrYYYYYYYYYYY** [comment]
> hack是我自己实现的，非hack的是原文的（非常难控制pose，需要大规模数据+overfit）

大佬，这里提到的hack具体是哪篇论文呀

**Comment by wangxr1999** [comment]
hello, loaded PoseGuider's pretrained weights from /mnt/home/code/workspace/AnimateAnyone-unofficial/outputs2/poseguider_stage_2.ckpt ...
Traceback (most recent call last):
  File "/opt/conda/envs/animate/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/animate/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/home/code/workspace/AnimateAnyone-unofficial/demo/animate_cli.py", line 37, in <module>
    animate_images(args)
  File "/mnt/home/code/workspace/AnimateAnyone-unofficial/demo/animate_cli.py", line 8, in animate_images
    animator = AnimateAnyone(config=args.config)
  File "/mnt/home/code/workspace/AnimateAnyone-unofficial/demo/animate.py", line 56, in __init__
    self.poseguider = PoseGuider.from_pretrained(pretrained_model_path=config.pretrained_poseguider_path)
  File "/mnt/home/code/workspace/AnimateAnyone-unofficial/models/hack_poseguider.py", line 92, in from_pretrained
    m, u = model.load_state_dict(state_dict, strict=False)
  File "/opt/conda/envs/animate/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Hack_PoseGuider:
        size mismatch for final_proj.weight: copying a param with shape torch.Size([4, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 128, 1, 1]).
        size mismatch for final_proj.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([320]). 
and also sample = sample + latent_pose [320, 128, 1, 1]+[4, 128, 1, 1] ,What is the reason for this？thanks
